# 'local' | 'development' | 'production'
nodeEnv: 'local'

server:
  port: 8000

postgres:
  uri: 'postgresql://root:root@localhost:5432/postgres'

redis:
  uri: 'redis://default:root@localhost:6379'

ttls:
  registrationSec: 600
  forgotPasswordSec: 600

codesLength:
  registration: 6
  forgotPassword: 6

salts:
  hashCredentials: 'superpuperextrasalt123'
  cryptoCredentials: 'superpuperextrasalt123'

jwt:
  accessTokenSecret: 'asd'
  refreshTokenSecret: 'asd'
  # 5 minutes
  accessTokenExpiry: 300000
  # 30 days
  refreshTokenExpiry: 2592000000
  issuer: 'family-time-api'

cookie:
  secret: 'askjdhfjb'
