# 'local' | 'development' | 'production'
nodeEnv: 'local'

server:
  port: 8000

postgres:
  uri: 'postgresql://root:root@localhost:5432/postgres'

redis:
  uri: 'redis://default:root@localhost:6379'

ttls:
  registrationSec: 600
  forgotPasswordSec: 600

codesLength:
  registration: 6
  forgotPassword: 6

salts:
  hashCredentials: 'superpuperextrasalt123'
  cryptoCredentials: 'superpuperextrasalt123'
  keyDerivation: 'lnbkhajbfbqi736qb73'

jwt:
  accessTokenSecret: 'asd'
  refreshTokenSecret: 'asd'
  accessTokenExpiry: '5m'
  refreshTokenExpiry: '30d'
  issuer: 'family-time-api'

cookie:
  secret: 'askjdhfjb'
